// Task pools and idle lines — extracted from game.js
// Loaded before game.js via <script> tag

const POOLS={
 dejan:{desc:'Glasses, Gromix, chain-smoker',home:{x:12,y:4},pool:[
   {type:'fetch',item:'cigs',itemLabel:'cigarettes',ask:"Out of cigs mid-deploy. Grab a pack from the kitchen.",reward:'Dejan lights up. "Now Gromix compiles. Thanks brother."'},
   {type:'fetch',item:'lighter',itemLabel:'a lighter',ask:"Got cigs, lost the lighter. Fetch me one, fast.",reward:'*click* "Ahh. Back to coding."'},
   {type:'mash',ask:"Prod is on fire — mash SPACE to force-redeploy!",reward:'"Green build. We never speak of this."'},
   {type:'type',word:'GROMIX',ask:"Type the deploy passphrase, both my hands are busy (cigarette).",reward:'"Deployed. Beautiful."'},
   {type:'math',ask:"Quick, how many API tokens left? Do the math.",reward:'"Correct. Rate limit dodged."'},
   {type:'scramble',word:'DEPLOY',ask:"Unscramble the command I forgot.",reward:'"That is the one. Shipping it."'},
   {type:'qte',ask:"Emergency hotfix combo — hit the keys, fast!",reward:'"Patched live. Legend."'},
   {type:'pincode',ask:"Memorize the server PIN before I forget it again.",reward:'"In. Nice memory."'},
   {type:'lockpick',ask:"Locked out of prod. Pick it open, carefully.",reward:'"We are in. Do not tell security."'},
   {type:'count',subject:'coffees today',ask:"How many coffees have I had today? I genuinely lost count.",reward:'"...that\'s a personal record. And it\'s not even lunch."'},
   {type:'hold',ask:"Take a drag with me while the build runs. Hold it... release at the right time.",reward:'*exhales* "Perfect timing. Build passed."'},
   {type:'typerace',word:'HOTFIX',ask:"Prod dies in seconds — type the fix before the timer!",reward:'"Saved with 0.3s to spare. Respect."'},
   {type:'crack',ask:"Guess which port the service died on. I'll say higher or lower.",reward:'"That is the one. Restarting now."'},
   {type:'jenga',ask:"Kill unused servers without taking down anything load-bearing.",reward:'"Infra is lean now. Nothing fell over."'},
   {type:'forge',recipe:['DB_URL','API_KEY','CACHE_ON'],extra:['DEBUG_MODE','COMIC_SANS'],ask:"Chain the env variables in the exact right order or it won't boot.",reward:'"Boots clean. You just saved my night."'},
   {type:'splice',pairs:[['/login','AuthService'],['/invoice','Billing'],['/upload','MediaStore']],hint:'Match each endpoint to its service.',ask:"Match each API endpoint to the service that actually owns it.",reward:'"All wired right. Now it actually works."'},
   {type:'noise',real:'ERR 502: gromix',fakes:['OK 200: gromix','OK 200: deploy','INFO: cache hit','INFO: ping ok','OK 200: auth'],hint:'Find the real ERROR in the logs.',ask:"One real error is buried in the logs. Find it.",reward:'"There is the bug. Everything else was noise."'},
   {type:'impostor',word:'works on my machine',odd:'works in prod',hint:'Four devs lie the same way. One tells the truth.',ask:"Four devs said the same thing. One is lying differently. Find them.",reward:'"Ha. Classic. Ship it anyway."'},
   {type:'priority',cards:[{l:'Prod is DOWN',p:1},{l:'Client demo in 1h',p:2},{l:'Code review',p:3},{l:'Update Jira',p:4}],hint:'What burns first?',ask:"Everything is on fire. Tell me what burns first.",reward:'"Correct. Jira can wait until 2027."'},
   {type:'jam',ask:"Printer ate the deploy sheet. Yank it out — mind the direction.",reward:'"Free. Now it prints. Barely."'},
   {type:'circuit',ask:"Server rack lost power. Re-route the wire tiles so it boots.",reward:'"Green lights. Gromix lives again."'},
   {type:'wire',pairs:[['HDMI','Projector'],['Ethernet','Router'],['Power','Wall socket']],hint:'Match each cable to the right port before the client demo.',ask:"Client demo in 2 minutes and nothing's plugged in right. Fix it.",reward:'"Screen\'s up. Cutting it close, but up."'},
   {type:'cartridge',hint:'Click each cartridge to cycle its color, match the label, then lock in.',ask:"Printer's out of ink and I need three colors right now. Load them right.",reward:'"Printing again. You just saved my afternoon."'},
   {type:'typewriter',word:'DEPLOY',ask:"Server's waiting. Type the deploy command letter by letter before the timeout.",reward:'"Green light. You type fast for a smoker."'},
   {type:'cableroute',ask:"Server rack is down. Route the power cable from source to the switch — no diagonal.",reward:'"Power restored. I owe you a coffee. Maybe."'},
   {type:'voltage',ask:"Three servers need constant power — keep all rails in green while the deploy runs.",reward:'"Stable the whole time. Respect."'},
   {type:'wordsearch',words:['CODE','BUG','LOG'],ask:"Find the three keywords buried in the error log grid.",reward:'"All found. You have the eyes of a grep command."'},
   {type:'toggle',hint:'Set switches to match the target server config.',ask:"Set the server flags to match the prod config — every switch matters.",reward:'"Flags match. Zero downtime. Legendary."'},
   {type:'binary',val:13,ask:"Convert server port 13 to binary — flip the right bulbs.",reward:'"Binary correct. You could work at NASA."'},
   {type:'mirror',word:'DEBUG',ask:"Terminal flipped on me — mirror mode. Type DEBUG normally to fix it.",reward:'"Fixed. Mirror mode, classic Dejan problem."'},
   {type:'park',ask:"Server room is full — parallel park the equipment rack into the last open slot. Don't scrape anything.",reward:'"Tight fit. Not a scratch. Respect."'},
   {type:'gauge',ask:"CPU temp is spiking — watch the gauge and tell me when it crosses the red line.",reward:'"Caught it at 94°. Throttled in time."'},
   {type:'switchboard',callerHint:'Nino calling about the server',hint:'Route Nino to the server room extension.',ask:"Switchboard's going crazy — route Nino to the right extension before he loses it.",reward:'"Connected. He only yelled a little."'},
   {type:'docsort',ask:"My Downloads folder is a disaster. Sort the files into the right project folders.",reward:'"Finally. I can find things again. Almost."'},
   {type:'recipe',ask:"New dev environment setup — follow the install steps in exact order or it breaks.",reward:'"Environment up. First try. Legendary."'},
   {type:'wordle',word:'CRASH',ask:"Server's down and I need to find the error type — guess the 5-letter word from the logs.",reward:'"CRASH. Exactly. Already fixed it, obviously."'},
   {type:'minesweeper',size:5,mines:4,ask:"Server maintenance grid — clear the safe nodes without triggering any faults.",reward:'"All clear. Zero incidents. Legendary maintenance."'},
   {type:'hidden',items:[{label:'USB',emoji:'🔌',x:40,y:30},{label:'Dongle',emoji:'🔑',x:180,y:120},{label:'Badge',emoji:'🪪',x:260,y:60}],ask:"Can't find the USB, dongle, and my access badge. They're on my desk... somewhere.",reward:'"Found them. The chaos has a system, I promise."'},
   {type:'typingtest',passage:'git commit -m "fix: resolve merge conflict in production branch"',ask:"Type this commit message exactly before the deploy window closes.",reward:'"Committed. Clean history. Legendary."'},
   {type:'pipe',size:4,ask:"Network routing diagram is broken — rotate the pipe segments to reconnect the server to the switch.",reward:'"Network restored. Packet loss: zero. Obviously."'},
   {type:'stamp',docs:['PR Review','Merge Request','Deploy Sign-off','Hotfix Approval'],ask:"Four docs need stamping before deploy. Get the order right.",reward:'"Stamped. Ship it."'},
   {type:'password',pw:'GROMIX',ask:"Gromix locked me out. Unscramble the password.",reward:'"Back in. Don\'t tell anyone the password."'},
   {type:'shredder',docs:['Old sprint plan','Draft v1','Draft v2','SSH key printout','Junk mail'],keep:'SSH key printout',ask:"Shred the old docs. Do NOT shred the SSH key printout.",reward:'"Good. That key is worth more than this building."'},
   {type:'expenses',threshold:200,items:[{name:'AWS bill',amount:180},{name:'Gold monitor stand',amount:450},{name:'USB hub',amount:35},{name:'Ergonomic keyboard',amount:120},{name:'Personal drone',amount:800}],ask:"Approve dev expenses under $200, reject the rest.",reward:'"Budget clean. Finance won\'t bother us."'},
   {type:'firewall',rounds:6,ask:"Production server's getting probed. Allow safe ports, block the sketchy ones.",reward:'"Firewall locked down. Zero breaches."'},
   {type:'receipt',items:[{name:'SSD',price:85},{name:'RAM stick',price:42},{name:'Cables',price:13},{name:'Fan',price:20}],ask:"Hardware receipt — add it up for the PO.",reward:'"Math checks out. Procurement approved."'},
   {type:'coffeeorder',count:3,ask:"Three devs need coffee. Memorize the order.",reward:'"Caffeinated and productive. Ship it."'},
   {type:'schedule',meetings:[{name:'Standup',slot:'9:00'},{name:'Code Review',slot:'11:00'},{name:'Deploy',slot:'15:00'},{name:'Retro',slot:'16:00'}],ask:"Schedule today's dev ceremonies. No conflicts.",reward:'"Calendar clean. No meeting collisions."'},
   {type:'rubberband',target:60,tol:12,ask:"Elastic deploy window — stretch to 60% and hold. Snap = rollback.",reward:'"Clean deploy. No rollback needed."'}
 ]},
 teonem:{desc:'Sales, always "out in town"',home:{x:10,y:9},pool:[
   {type:'deliver',item:'contract',itemLabel:'contract',to:'nino',ask:"Running into town (work!). Take this contract to Nino.",reward:'"Legend. I never left, clear?" *left*'},
   {type:'choose',q:'Client wants a discount. Best move?',opts:[{t:'Offer a bundle',ok:true},{t:'Say no, hang up',ok:false},{t:'Ghost them',ok:false}],ask:"Coach me — client wants a discount.",reward:'"Closed it from the parking lot."'},
   {type:'timing',ask:"Calling a lead NOW — nail the send timing.",reward:'"Perfect timing. Signed."'},
   {type:'reflex',ask:"Lead picks up any second. Click GO the instant it appears.",reward:'"Caught them on ring one. Out."'},
   {type:'hold',ask:"Busy CEO won't pick up — leave a voicemail. Hold SPACE, release right in the sweet spot.",reward:'"Reply in 2 min. Boom."'},
   {type:'dodge',ask:"Dodging awkward questions in the sales meeting — weave through!",reward:'"Deflected every one. Still closed."'},
   {type:'slider',ask:"Dial the discount to the exact sweet spot. Not a cent more.",reward:'"Perfect margin. That is the job."'},
   {type:'rhythm',ask:"Small talk has a rhythm. Match it, land the deal.",reward:'"Smooth as ever. Out the door."'},
   {type:'impostor',word:'READY TO BUY',odd:'JUST BROWSING',hint:'Four are buyers. Spot the time-waster.',ask:"One lead is a time-waster. Spot the odd one.",reward:'"Knew it. Not wasting my time."'},
   {type:'higherlower',ask:"Two offers on the table — always grab the bigger one. Three rounds.",reward:'"Maximum value, every time."'},
   {type:'moving',ask:"This client keeps dodging my calls — catch him! He moves.",reward:'"Cornered him by the printer. Signed."'},
   {type:'target',ask:"Build me a bundle that hits the exact price target.",reward:'"To the cent. You are wasted here."'},
   {type:'budget',ask:"Split my commission between three deals so it adds up right.",reward:'"Exactly what I earned. Nice math."'},
   {type:'rank',items:['Signed LOI, wants call NOW','Asked for a quote','Opened the email twice','Unsubscribed (twice)'],hint:'Drag hottest lead to the top.',ask:"Rank these leads hottest to coldest before they go cold for real.",reward:'"Perfect order. That is how deals get closed."'},
   {type:'crack',ask:"Guess this client's real budget. I'll tell you higher or lower.",reward:'"Nailed it. Now watch me close this."'},
   {type:'signal',ask:"Catch the client mid-call at exactly the right beat to pitch.",reward:'"Timed it perfect. Pitch landed."'},
   {type:'overload',ask:"Two leads calling in at once — keep both warm, don't drop either.",reward:'"Both closed. I contain multitudes."'},
   {type:'splice',pairs:[['Objection: too expensive','Show ROI math'],['Objection: no time','Offer 15-min call'],['Objection: thinking','Book follow-up date']],hint:'Match each objection to the counter.',ask:"Match each client objection to the right counter-move.",reward:'"Textbook. You could sell air."'},
   {type:'calendar',ask:"Book me three demos this week — no clashes, I'm 'in town' a lot.",reward:'"Slotted clean. I close from anywhere."'},
   {type:'maze',ask:"Move this car to the showroom floor for me — don't scuff anything on the way.",reward:'"Parked pretty. Client\'s gonna love it."'},
   {type:'handover',steps:['Greet the client','Check their ID & paperwork','Walk them around the car','Explain the key features','Hand over the keys','Wave them off'],hint:'Client\'s here for the car. Do the handover in the right order.',ask:"Handover time. Client's here for the car — do it right, step by step.",reward:'"Perfect handover. That\'s a referral right there."'},
   {type:'flowchart',tree:{q:'Client says too expensive?',yes:{q:'Offer a smaller package?',yes:{end:true,win:true},no:{end:true,win:false}},no:{q:'Close now?',yes:{end:true,win:true},no:{end:true,win:false}}},hint:'Follow the sales decision tree.',ask:"Walk the decision tree — what do I do with this client right now?",reward:'"Textbook close. Beautiful."'},
   {type:'inbox',emails:[{from:'Hot lead',sub:'Ready to sign contract',type:'urgent'},{from:'promo@deals.biz',sub:'Double commission offer!!!',type:'spam'},{from:'Steve',sub:'Follow-up with Zagreb client',type:'urgent'},{from:'newsletter@crm.io',sub:'CRM tips weekly digest',type:'safe'},{from:'unknown@fishy.net',sub:'Your account suspended',type:'spam'}],ask:"Clear my inbox before the client meeting — flag urgent, archive safe, delete spam.",reward:'"Inbox zero. Teonem is unstoppable."'},
   {type:'conveyor',target:'\uD83D\uDCCB',fakes:['\uD83D\uDCE7','\uD83D\uDCC1','\uD83D\uDCF1'],ask:"Contracts rolling in on the belt — grab the clipboards, ignore everything else.",reward:'"All contracts caught. Efficiency is beautiful."'},
   {type:'triage',cards:[{label:'Client ready to sign',bucket:'urgent'},{label:'Cold lead newsletter',bucket:'archive'},{label:'Follow-up in a week',bucket:'normal'},{label:'Demo request today',bucket:'urgent'},{label:'Unsubscribed prospect',bucket:'archive'}],ask:"Triage my sales pipeline — urgent, normal, or archive each one.",reward:'"Perfect sort. That is a clean pipeline."'},
   {type:'frequency',target:101,hint:'Tune the radio for the client drive — exactly 101.0 FM.',ask:"Set the car radio to 101.0 before the client gets in. Nothing worse than static.",reward:'"101.0. Smooth. Client is already impressed."'},
   {type:'approvalchain',chain:['Sales Rep','Team Lead','Sales Director','CEO'],hint:'Who approves a large deal, step by step?',ask:"Big deal needs sign-off up the chain — click each approver in the right order.",reward:'"Approved at every level. Deal\'s done."'},
   {type:'slot',target:[2,2,2],hint:'Stop all three reels on the checkmark.',ask:"Three clients all say yes at once — stop the reels on the triple win!",reward:'"Triple close. I can\'t even explain this."'},
   {type:'inspect',ask:"Client returning the demo car — find every scratch and dent before he claims it was there before.",reward:'"Four scratches. Two definitely his. Documentation saves lives."'},
   {type:'arrange',items:[['🔑','keys'],['📋','contract'],['🪪','id']],hint:'Lay out the handover items in the exact order.',ask:"Set up the delivery table before the client arrives — keys, contract, ID in my exact order.",reward:'"Perfect setup. First impressions close deals."'},
   {type:'barcode',ask:"New stock just arrived from the importer — scan each VIN barcode. Steady hand.",reward:'"All logged. Inventory updated. Clean."'},
   {type:'safe',ask:"Commission envelope's in the office safe — crack it before Nino gets back.",reward:'"Opened. Commission secured. Teonem was never here."'},
   {type:'spy',ask:"Competitor's price list is on the table — find the Golf price before they notice.",reward:'"Got it. We\'re cheaper by 800. Beautiful."'},
   {type:'flowfree',size:5,pairs:[{color:'#e03030',from:[0,0],to:[4,3]},{color:'#2e7d46',from:[0,4],to:[3,0]},{color:'#1565c0',from:[1,2],to:[4,1]},{color:'#b07d18',from:[0,2],to:[4,4]}],ask:"Route the client calls through the switchboard — connect every line without crossing them.",reward:'"All lines clear. Every client reached. Beautiful."'},
   {type:'merge2048',target:128,ask:"Budget spreadsheet — merge the numbers until you hit the quarterly target.",reward:'"128k. Nailed it. Commission incoming."'},
   {type:'wordle',word:'LEASE',ask:"Client mentioned the deal type but I forgot — guess the 5-letter word.",reward:'"LEASE. Of course. Three-year term, standard."'},
   {type:'hidden',items:[{label:'Contract',emoji:'📋',x:60,y:40},{label:'Keys',emoji:'🔑',x:200,y:130},{label:'Card',emoji:'💳',x:120,y:90}],ask:"Demo car keys, the contract, and the client's card are buried on my desk. Find them.",reward:'"Found everything. Now the handover can happen."'},
   {type:'tetris',lines:3,ask:"Car parts just came in — stack them in the warehouse so nothing falls over. Clear 3 rows.",reward:'"Stacked clean. Nino will never know it was chaos."'},
   {type:'elevator',floor:7,ask:"Client meeting is on floor 7. Stop the elevator right.",reward:'"Smooth ride. First impressions matter."'},
   {type:'phonetree',target:'International',ask:"Call HQ — navigate to International Sales.",reward:'"Connected. Time to close the deal from the parking lot."'},
   {type:'copier',rounds:3,ask:"Copy these contracts before the client leaves. Hit green, miss red.",reward:'"Three clean copies. Professional."'},
   {type:'expenses',threshold:150,items:[{name:'Client lunch',amount:90},{name:'Parking',amount:15},{name:'Private jet fuel',amount:4200},{name:'Hotel room',amount:140},{name:'Champagne',amount:380}],ask:"Expense report time. Approve under $150.",reward:'"Clean expenses. Nino won\'t question a thing."'},
   {type:'pingpong',rallies:5,ask:"Break room ping pong with the client. Keep the rally going — close deals over paddles.",reward:'"Five rallies. Client impressed. Deal as good as done."'},
   {type:'namecard',names:['Babic','Cvijanovic','Djordjevic','Jovanovic','Markovic'],ask:"Sort these client business cards alphabetically. Gotta look organized.",reward:'"Sorted. Rolodex game strong."'},
   {type:'receipt',items:[{name:'Fuel',price:55},{name:'Toll',price:12},{name:'Parking',price:8},{name:'Lunch',price:32},{name:'Coffee',price:5}],ask:"Add up today's road trip expenses for the report.",reward:'"112 dinara... wait, that\'s euros. Either way, approved."'},
   {type:'schedule',meetings:[{name:'Cold call',slot:'9:00'},{name:'Client demo',slot:'11:00'},{name:'Lunch deal',slot:'13:00'},{name:'Follow-up',slot:'15:00'}],ask:"Schedule my sales day. Don't double-book me.",reward:'"Perfect calendar. Time to hit the road."'},
   {type:'coffeeorder',count:4,ask:"Buying coffee for the whole client meeting. Remember who gets what.",reward:'"Four coffees, four happy clients. That\'s how deals happen."'},
   {type:'firewall',rounds:5,ask:"Office VPN acting up. Check which ports are legit.",reward:'"Network clean. Back to selling from the parking lot."'},
   {type:'rubberband',target:70,tol:10,ask:"Price negotiation — stretch the offer to 70%. Don't break it.",reward:'"Clean stretch. Client says yes."'},
   {type:'receipt',items:[{name:'Demo car wash',price:15},{name:'Client gift',price:40},{name:'Gas',price:55},{name:'Snacks',price:10}],ask:"Road trip expenses. Add them up before Nino asks.",reward:'"120. Submitted. Nino won\'t blink."'}
 ]},
 steve:{desc:'Beard, vape, sells in Croatia',home:{x:4,y:2},pool:[
   {type:'fetch',item:'vape',itemLabel:'vape',ask:"Left my vape by the entrance. No fog, no deals.",reward:'*huge cloud* "Now we do business."'},
   {type:'timing',ask:"Calling Zagreb — catch the second to drop the offer.",reward:'"Bang on. Respect." *vapor*'},
   {type:'typerace',word:'RAZMISLITCU',ask:"Type the Croatian phrase back before the timer — prove you were listening.",reward:'"Tocno. You get it."'},
   {type:'scramble',word:'ZAGREB',word:'CRNOMELJA',ask:"Unscramble where Teonem is actually from.",reward:'"Točno! Iz Črnomelja!"'},
   {type:'mash',ask:"Vape battery died — mash SPACE to charge it back!",reward:'*puff* "Alive again. Deals incoming."'},
   {type:'colormatch',ask:"Match my new vape color, obviously important.",reward:'"That is the shade. Classy clouds."'},
   {type:'trace',ask:"Trace the drive route to the Zagreb client, in order.",reward:'"Fastest way there. Let us go."'},
   {type:'whack',ask:"Notifications blowing up from Croatia — tap them all!",reward:'"Cleared. All deals, no spam."'},
   {type:'balance',ask:"Balance the vape on the desk while I talk. Steady.",reward:'"Did not drop it once. Pro."'},
   {type:'hold',ask:"Longest drag contest. Hold SPACE... release in the green.",reward:'*cloud fills the room* "Champion."'},
   {type:'higherlower',ask:"Compare these Croatian offers — pick the bigger, three times.",reward:'"Uvijek veca ponuda. Always."'},
   {type:'maze',ask:"Route the delivery van through Zagreb traffic without a scratch.",reward:'"Made it in one piece. Barely."'},
   {type:'noise',real:'Order: 10 units, Zagreb',fakes:['YOU WON $$$','FREE CRYPTO 4U','HOT DEAL CLICK','PRINCE NEEDS HELP','LAST WARNING!!'],hint:'Find the real client order in the spam.',ask:"Client sent one real message buried in a spam thread. Find it.",reward:'"There it is. The rest was noise, as usual."'},
   {type:'budget',ask:"Split territory between me and the other rep. Fair, but mostly mine.",reward:'"Perfect split. Mostly mine, like I said."'},
   {type:'forge',recipe:['SMALL TALK','PITCH','DISCOUNT'],extra:['HARD SELL','INVOICE FIRST'],ask:"Build the sales call in the right order — don't blow the deal.",reward:'"That combo closed it. Smooth."'},
   {type:'signal',ask:"Catch the call the instant it connects across the border.",reward:'"Connected clean. No lag, no lost deal."'},
   {type:'splice',pairs:[['Dobar dan','Good day'],['Racun, molim','Invoice, please'],['Dogovoreno','Deal']],hint:'Match Croatian to English.',ask:"Match my Croatian phrases so I don't embarrass myself in Zagreb.",reward:'"Bok! Now I sound like a local."'},
   {type:'qralign',ask:"Scan this Croatian client's QR invoice — line it up, hold steady.",reward:'*vapor* "Locked. Deal logged."'},
   {type:'patchline',pairs:[['Golf GTI','ZG-341-KL'],['Passat','ZG-852-MN'],['Octavia','ZG-119-RT']],hint:'Drag a line from each car to its plate.',ask:"Match each car on the lot to its actual plate. Zagreb inventory's a mess.",reward:'*vapor* "All matched. Inventory\'s clean."'},
   {type:'crack',ask:"Which car is the client asking about? I'll say warmer or colder on the stock number.",reward:'*vapor* "That\'s the one. Good guess, chief."'},
   {type:'barcode',ask:"Parts shipment just came in from Zagreb — scan it in. Steady hand, not too fast.",reward:'*vapor* "Logged. Croatia never disappoints."'},
   {type:'redact',sentences:['Client name: Marko Horvat signed today','Contact: +385 91 555 0192','Bank: IBAN HR1234567890123456'],sensitive:['Marko Horvat','+385 91 555 0192','HR1234567890123456'],ask:"Redact the client data before sending this to the wrong department. *vapor*",reward:'*vapor* "Clean send. Privacy intact."'},
   {type:'hotkey',items:[{k:'S',l:'Save'},{k:'P',l:'Print'},{k:'E',l:'Export'},{k:'C',l:'Close'}],target:'P',ask:"Print the contract — keyboard only, no mouse. That is how pros do it.",reward:'*vapor* "Printed. Respect."'},
   {type:'cipher',shift:3,raw:'INVOICE',ask:"Client sent an encoded message — shift 3 letters to decode. Which shift is it?",reward:'*vapor* "Decoded. Classic Caesar. Old school."'},
   {type:'contract',fields:['Supplier signature','Date','Reference number'],ask:"Supplier contract came in — scroll through and sign every field before it expires.",reward:'*vapor* "All signed. Deal\'s locked."'},
   {type:'handover',steps:['Greet the client','Verify ID and registration','Walk around the car together','Explain the warranty','Hand over the keys','Wave them off'],hint:'Croatian client handover — every step matters.',ask:"Zagreb client picking up their car. Do the handover properly — step by step. *vapor*",reward:'*vapor* "Flawless. That\'s a five-star review."'},
   {type:'calendar',ask:"Schedule the Zagreb client visit — find the free slot this week that works across time zones.",reward:'*vapor* "Booked. Croatia never sleeps."'},
   {type:'rotary',combo:[30,60,10],hint:'Spin to each number and press SET.',ask:"Office safe with the Croatian contracts — spin the combo before the courier leaves.",reward:'*vapor* "Opened. Contracts secured."'},
   {type:'heatmap',zones:['Zagreb','Split','Rijeka','Osijek'],hotIdx:0,hint:'Which territory is generating most leads right now?',ask:"Look at the territory heatmap — where should I focus this week?",reward:'*vapor* "Zagreb. Always Zagreb."'},
   {type:'dragfile',ask:"Client files from Zagreb are in the wrong folders again — drag them to the right place.",reward:'*vapor* "Organized. I can find things now."'},
   {type:'wordle',word:'SPLIT',ask:"Croatian city where the big client is based — guess the 5-letter word. *vapor*",reward:'*vapor* "SPLIT. Exactly. Road trip incoming."'},
   {type:'minesweeper',size:5,mines:3,ask:"Territory map has dead zones — clear the safe areas without hitting a bad lead.",reward:'*vapor* "Clean territory. Every safe lead flagged."'},
   {type:'hidden',items:[{label:'Vape',emoji:'💨',x:80,y:50},{label:'Offer',emoji:'📄',x:220,y:110},{label:'Phone',emoji:'📱',x:150,y:150}],ask:"Can't find my vape, the offer letter, and my phone before the client call. *vapor*",reward:'*vapor* "All found. Call starts in 30 seconds."'},
   {type:'flowfree',size:4,pairs:[{color:'#e03030',from:[0,0],to:[3,3]},{color:'#2e7d46',from:[0,3],to:[3,0]},{color:'#1565c0',from:[0,1],to:[2,3]}],ask:"Route the Croatian territory sales calls — connect every region without overlap.",reward:'*vapor* "All regions covered. Clean map."'},
   {type:'tetris',lines:3,ask:"Parts shipment from Zagreb — stack the boxes in the storage bay before the truck leaves. *vapor*",reward:'*vapor* "Clean stack. Zero damage. Professional."'},
   {type:'typingtest',passage:'Poštovani klijente, šaljemo Vam ponudu u prilogu.',ask:"Type this Croatian client email exactly — one typo and the deal looks amateur. *vapor*",reward:'*vapor* "Sent. Professional. Croatian clients expect nothing less."'},
   {type:'stamp',docs:['Import Form','Export Cert','Customs Declaration','Insurance'],ask:"*vapor* Stamp these trade docs before customs closes.",reward:'*vapor* "Stamped and shipped. Zagreb gets it tomorrow."'},
   {type:'waterplant',target:70,tol:12,ask:"*vapor* Water the office plants. Don't overdo it — kill a fern, kill the vibe.",reward:'*vapor* "Perfect. Even the plants vape around me."'},
   {type:'filing',files:[{name:'Zagreb contract',cab:'Sales'},{name:'Split invoice',cab:'Finance'},{name:'Visa receipt',cab:'Travel'},{name:'Commission calc',cab:'Finance'}],ask:"*vapor* File these Croatian docs. Wrong drawer = Nino finds out.",reward:'*vapor* "Filed. Organized. Nino suspects nothing."'},
   {type:'rubberband',target:55,tol:10,ask:"*vapor* Price negotiation — stretch the margin to 55%. Don't snap the deal.",reward:'*vapor* "Clean margin. Client happy. Vape happy."'},
   {type:'pingpong',rallies:4,ask:"*vapor* Quick game with the warehouse guys in Split. Keep the rally.",reward:'*vapor* "Four rallies. Croatian warehouse respects me now."'},
   {type:'firewall',rounds:5,ask:"*vapor* IT asked to check the VPN. Allow legit ports, block the rest.",reward:'*vapor* "Secured. Even the firewall vapes."'},
   {type:'receipt',items:[{name:'Vape juice',price:18},{name:'Coils',price:12},{name:'Battery',price:25},{name:'Case',price:15}],ask:"*vapor* Vape supply receipt. Add it up before the wife checks.",reward:'*vapor* "70 total. Reasonable. Don\'t tell anyone."'},
   {type:'namecard',names:['Babic','Horvat','Kovacevic','Petrovic','Tomic'],ask:"*vapor* Sort the Croatian client cards. Alphabetical. Professional.",reward:'*vapor* "Sorted. Every card in place."'},
   {type:'schedule',meetings:[{name:'Morning vape',slot:'9:00'},{name:'Client call',slot:'11:00'},{name:'Site visit',slot:'14:00'},{name:'Report',slot:'16:00'}],ask:"*vapor* Schedule the day. No double-booking the vape breaks.",reward:'*vapor* "Calendar locked. Efficient."'},
   {type:'coffeeorder',count:3,ask:"*vapor* Three Croatians need coffee. Remember who gets what.",reward:'*vapor* "Three happy clients. Vape break earned."'},
   {type:'elevator',floor:5,ask:"*vapor* Meeting on floor 5. Nail the stop.",reward:'*vapor* "Smooth arrival. Professional."'},
   {type:'rubberband',target:50,tol:10,ask:"*vapor* Margin negotiation — stretch to 50%. Don't snap.",reward:'*vapor* "Perfect margin. Deal holds."'},
   {type:'waterplant',target:55,tol:10,ask:"*vapor* Office fern by the window. Water it. Don't drown it.",reward:'*vapor* "Green and healthy. Like my vape juice."'}
 ]},
 brana:{desc:'Watches everyone (secretly)',home:{x:3,y:9},pool:[
   {type:'fetch',item:'logsheet',itemLabel:'attendance log',ask:"Bring that sheet by the entrance. I do not track people... just get it.",reward:'*hides it* "I did not ask for this. But I did."'},
   {type:'memory',ask:"Recall the exact order people arrived. I was not watching, obviously.",reward:'"Correct. Not that I keep records. (I do.)"'},
   {type:'rolodex',cards:['Sonja — 08:58','Pedja — 09:02','Nina — 09:04','Teonem — 09:47 ("errands")'],correctIdx:3,ask:"Between us... who was last?",reward:'*scribbles* "Thought so."'},
   {type:'sequence',ask:"Play back today's clock-in order on the grid.",reward:'"Flawless. This never happened."'},
   {type:'avoid',ask:"Flag the late arrivals, skip the punctual ones.",reward:'"Efficient. I trained you well."'},
   {type:'spotdiff',ask:"One timesheet does not match the rest. Find it.",reward:'"There it is. Someone fudged it."'},
   {type:'pincode',ask:"Memorize the door access code. For records.",reward:'"Logged. I remember everything."'},
   {type:'sortorder',ask:"Put the clock-in times in order for me.",reward:'"Perfectly sorted. As always."'},
   {type:'count',ask:"Count how many left early on Friday.",reward:'"Mhm. Thought it was that many."'},
   {type:'pairs',ask:"Match each badge to its owner. From memory. Which I do not keep.",reward:'"All matched. You would make a fine... observer."'},
   {type:'gridmem',ask:"Which desks were occupied at 9:01? Mark them.",reward:'"Exactly right. (I have it on camera anyway.)"'},
   {type:'oddeven',ask:"Sort these clock-ins: even minutes = on time, odd = late.",reward:'"Sorted. The odd ones will be... noted."'},
   {type:'spy',ask:"Memorize who sat where this morning. I definitely was not watching.",reward:'"Correct. (I was watching.)"'},
   {type:'echo',ask:"Repeat back the growing list of who left early. Do not skip anyone.",reward:'"All accounted for. Good memory."'},
   {type:'dial',hint:'Dial in the drawer combination.',ask:"Guess the drawer combination. Don't ask why I know it.",reward:'"Cracked. I am impressed. Slightly concerned."'},
   {type:'rank',items:['Someone got a raise (WHO?)','Fridge thief struck again','Parking spot dispute','Stapler was moved 3cm'],hint:'Drag the juiciest gossip to the top.',ask:"Rank the office gossip by how juicy it is. Highest first.",reward:'"Exactly my ranking. We think alike."'},
   {type:'splice',pairs:[['Teonem','arrived 09:47'],['Steve','arrived 08:55'],['Pedja','arrived 08:30']],hint:'Match each person to their arrival time.',ask:"Match each person to when they REALLY arrived. I have it memorized. Allegedly.",reward:'"All correct. I always know. Always."'},
   {type:'impostor',word:'I was here at 8:00',odd:'traffic was crazy',hint:'Four honest, one excuse.',ask:"Five people told me when they arrived. One is making excuses. Spot it.",reward:'"Noted. Filed. Never mentioned again. (Mentioned daily.)"'},
   {type:'docsort',ask:"Stamp the signed timesheets, reject the blanks. I'm... auditing.",reward:'"All sorted. Nothing gets past me."'},
   {type:'switchboard',opts:['Dejan (IT)','Sonja (Payroll)','Reception'],correctIdx:0,callerHint:'IT issue — Sonja\'s PC crashed',ask:"Phone's ringing. I know exactly who needs this, obviously — do you?",reward:'"Correct. I was testing you."'},
   {type:'priority',cards:[{l:'Get everyone to the exit',p:1},{l:'Call the fire department',p:2},{l:'Grab the visitor log',p:3},{l:'Lock your desk',p:4}],hint:'Drill\'s starting. What matters first?',ask:"Fire drill. I've mentally rehearsed this daily — what happens first?",reward:'"Correct. I would know."'},
   {type:'crack',ask:"This visitor badge doesn't look right to me. Higher or lower — guess the real badge number.",reward:'"Fake. I knew it. I know everything."'},
   {type:'typewriter',word:'WATCHING',ask:"Type what I\'m always doing — letter by letter before they fall.",reward:'"Correct. Though I prefer to deny it."'},
   {type:'crossword',clues:[{hint:'Opposite of punctual (4 letters)',ans:'LATE'},{hint:'I always secretly... (5 letters)',ans:'WATCH'},{hint:'What I write about everyone (5 letters)',ans:'NOTES'}],ask:"Fill in my attendance crossword. I may have prepared this.",reward:'"All correct. I always knew you were paying attention."'},
   {type:'wordsearch',words:['LATE','WATCH','NOTE'],ask:"Find the surveillance keywords I definitely do not track. In this grid. Allegedly.",reward:'"Found them all. I had nothing to do with it."'},
   {type:'triage',cards:[{label:'Someone arrived late',bucket:'urgent'},{label:'Birthday card signing',bucket:'normal'},{label:'Old meeting notes',bucket:'archive'},{label:'Attendance discrepancy',bucket:'urgent'},{label:'Lunch order spam',bucket:'archive'}],ask:"Triage these office incidents. I have a system. I always have a system.",reward:'"Exactly my order. We are aligned."'},
   {type:'approvalchain',chain:['Employee','HR','Manager','Brana'],hint:'Absence form goes up the chain. Who signs last?',ask:"Someone filed an absence form. Route it up the chain in the right order.",reward:'"Filed. Chronologically. Immaculately."'},
   {type:'voicemail',pool:['Tuesday','Thursday','Friday','Monday','Wednesday'],ask:"Someone left a day-by-day voicemail — remember and type back only the LAST day mentioned.",reward:'"Correct. I already knew, but I tested you."'},
   {type:'binary',val:7,ask:"Access code for the archive room is 7 in binary. Set the light panel correctly.",reward:'"Correct pattern. The archive is yours. Briefly."'},
   {type:'stopwatch',ms:3000,ask:"Time how long Teonem's been gone. Stop the watch at exactly 3 seconds — I\'m calibrating my estimates.",reward:'"3.0 seconds. My internal clock was right. As always."'},
   {type:'dodge',ask:"HR memo flood — dodge the irrelevant ones, let the important ones through.",reward:'"Perfect filter. I read everything anyway."'},
   {type:'jam',ask:"Office printer jammed mid-document — clear the jam sequence before anyone notices.",reward:'"Unjammed. Document: attendance report. Asking for a friend."'},
   {type:'qralign',ask:"Visitor badge QR needs scanning — line it up before they realize I\'ve been watching.",reward:'"Scanned. Visitor logged. I do not track people."'},
   {type:'inbox',emails:[{from:'Teonem',sub:'Working from "client site"',type:'spam'},{from:'HR',sub:'Attendance policy update',type:'urgent'},{from:'Pedja',sub:'Lunch order question',type:'safe'},{from:'Unknown',sub:'You\'ve been selected!',type:'spam'},{from:'Nino',sub:'Staff meeting NOW',type:'urgent'}],ask:"My inbox has noise. Flag urgent, file safe, delete spam. You know the drill.",reward:'"Perfect sort. I would have done the same. Exactly the same."'},
   {type:'wordle',word:'WATCH',ask:"Five letters. What I always do. Guess it.",reward:'"WATCH. Correct. I neither confirm nor deny."'},
   {type:'minesweeper',size:4,mines:3,ask:"Office seating grid — identify the problem areas without triggering a complaint.",reward:'"All clear. Problems identified. Quietly noted."'},
   {type:'hidden',items:[{label:'Log',emoji:'📒',x:50,y:60},{label:'Badge',emoji:'🪪',x:190,y:100},{label:'Pen',emoji:'🖊️',x:260,y:150}],ask:"My observation log, a visitor badge, and my pen — find them in this desk mess.",reward:'"All found. The system works. I have a system."'},
   {type:'merge2048',target:64,ask:"Attendance numbers — merge the daily counts into the weekly total.",reward:'"64. Exactly right. Every head counted."'},
   {type:'pipe',size:4,ask:"Office network cable layout needs fixing — rotate the segments to reconnect every desk without loops.",reward:'"Connected. Every desk online. I was watching the whole time."'},
   {type:'typingtest',passage:'All staff are reminded that arrival before 09:00 is mandatory.',ask:"Type this memo exactly — every character matters when you're documenting attendance policy.",reward:'"Typed and sent. Timestamped. Filed. Obviously."'},
   {type:'shredder',docs:['Old schedule','Break log','Incident report','Vacation form','Complaint draft'],keep:'Incident report',ask:"Shred these. Keep the incident report — I'll need it later.",reward:'"Good. That report stays in my drawer."'},
   {type:'copier',rounds:5,ask:"Copy the surveillance summaries. Five copies, no errors.",reward:'"Five clean copies. One for each person I\'m watching."'},
   {type:'stamp',docs:['Attendance Log','Tardiness Report','NPC Movement Sheet','Exit Records'],ask:"Stamp these tracking documents in order.",reward:'"Stamped. Every minute accounted for."'},
   {type:'password',pw:'WATCH',ask:"My tracking spreadsheet is locked. Unscramble it.",reward:'"Back in. I see everything again."'},
   {type:'schedule',meetings:[{name:'Surveillance',slot:'9:00'},{name:'Report Filing',slot:'11:00'},{name:'Lunch Watch',slot:'13:00'},{name:'Exit Monitoring',slot:'16:00'}],ask:"Schedule my observation shifts. I need full coverage.",reward:'"Full day covered. Nobody escapes."'},
   {type:'namecard',names:['Dejan','Daniel','Nina','Pedja','Steve'],ask:"Sort the personnel files alphabetically. For... reference.",reward:'"Sorted. Cross-referenced with my notes."'},
   {type:'receipt',items:[{name:'Binoculars',price:35},{name:'Notebook',price:8},{name:'Pen set',price:12},{name:'Hidden camera',price:45}],ask:"Surveillance supply receipt. Add it up. Quietly.",reward:'"100. All accounted for. Tax deductible."'},
   {type:'coffeeorder',count:3,ask:"Three people just ordered coffee. I need to know who drinks what. For the file.",reward:'"Noted. Coffee preferences logged."'},
   {type:'firewall',rounds:5,ask:"Someone's accessing restricted files. Check the ports.",reward:'"Blocked. I see everything on this network too."'}
 ]},
 sonja:{desc:'Quiet, runs payroll',home:{x:4,y:11},pool:[
   {type:'deliver',item:'router',itemLabel:'the router',to:'nino',ask:"Payroll needs internet. Give the router to Steve — he's the IT guy.",reward:'barely audible: "...thank you."'},
   {type:'type',word:'PAYROLL',ask:"Type the confirmation so salaries send. Quietly.",reward:'*nods* "Sent." *whisper*'},
   {type:'math',ask:"Double-check this payslip total for me?",reward:'"...exact. Good." *soft smile*'},
   {type:'fetch',item:'invoice',itemLabel:'an invoice',ask:"An invoice is on the far desk. Bring it, please.",reward:'"...perfect. Filed."'},
   {type:'pincode',ask:"Remember the payroll safe code. Do not say it aloud.",reward:'*nods slowly* "...correct."'},
   {type:'slider',ask:"Set the bonus rate to the agreed number. Exactly.",reward:'"...that is it. Approved." *whisper*'},
   {type:'sortorder',ask:"Order these payslips by amount. Quietly.",reward:'"...sorted. Thank you."'},
   {type:'count',ask:"Count the pending reimbursements for me?",reward:'"...yes. That many. Noted."'},
   {type:'target',ask:"Pick amounts that sum exactly to the payroll total.",reward:'"...balanced to the cent. Rare."'},
   {type:'oddeven',ask:"Valid invoices are even, odd are errors. Sort them, please.",reward:'"...all correct. So quiet. So precise."'},
   {type:'typerace',word:'APPROVED',ask:"Bank portal times out fast — type it before the clock!",reward:'"...made it. Everyone gets paid."'},
   {type:'dial',hint:'Dial in the safe combination.',ask:"Guess the safe combination. Not that I would ever forget it myself.",reward:'"...got it. Not that I would ever forget it myself."'},
   {type:'budget',ask:"Split this bonus pool so it adds up exactly. No more, no less.",reward:'"...balanced perfectly. Thank you."'},
   {type:'splice',pairs:[['ID-104 (junior)','\u20ac1.450'],['ID-207 (senior)','\u20ac2.900'],['ID-311 (intern)','\u20ac600']],hint:'Match each employee to the right salary.',ask:"Match each employee ID to their salary line. Quietly.",reward:'"...all matched. Nobody overpaid. Nobody underpaid."'},
   {type:'echo',ask:"Repeat this growing account number back to me. Do not lose a digit.",reward:'"...correct. Every digit." *whisper*'},
   {type:'noise',real:'INV-207 \u20ac1.850 DUE',fakes:['INV-201 \u20ac920 PAID','INV-114 \u20ac340 PAID','INV-166 \u20ac780 PAID','INV-090 \u20ac210 PAID'],hint:'Find the one UNPAID invoice.',ask:"One invoice in this ledger is still unpaid. Find it.",reward:'"...there it is. Caught before it caused trouble."'},
   {type:'priority',cards:[{l:'Salaries (today!)',p:1},{l:'Office rent',p:2},{l:'Software licenses',p:3},{l:"Nino's new chair",p:4}],hint:'What gets paid first?',ask:"Not everything can be paid today. Order the payments, please.",reward:'"...salaries first. Always. Good."'},
   {type:'cash',ask:"Count the petty-cash drawer to the exact figure. Quietly.",reward:'"...balances to the cent. Perfect."'},
   {type:'choose',q:'Payroll hotline is ringing — pick the professional reply.',opts:[{t:'"Payroll, this is Sonja, how can I help?"',ok:true},{t:'"What."',ok:false},{t:'"Call back later, obviously."',ok:false}],ask:"Phone won't stop ringing. Answer it properly, please.",reward:'"...good. Professional. Quietly proud."'},
   {type:'memory',ask:"Remember the voicemail number, then play it back for me. Quietly.",reward:'"...correct. Not one digit off."'},
   {type:'budgetslider',targets:[40,35,25],labels:['Salaries','Operations','Reserves'],ask:"Set the budget split to the agreed percentages. Exactly.",reward:'"...precise. That\'s the word."'},
   {type:'redact',sentences:['Salary: EUR 2850 gross for Teonem','Bonus: EUR 400 approved by Nino','Account: HR9876543210987654'],sensitive:['EUR 2850','EUR 400','HR9876543210987654'],ask:"This payslip must not leave with numbers visible. Redact.",reward:'"...thank you. Quietly."'},
   {type:'rotary',combo:[20,50,80],hint:'Spin to each number and press SET.',ask:"Spin the petty cash safe combination. Slowly. Exactly.",reward:'"...correct. Every cent accounted for."'},
   {type:'contract',fields:['Employee signature','HR signature','Effective date'],ask:"New hire contract needs every field signed before their start date. Scroll and sign.",reward:'"...filed. Quietly."'},
   {type:'toggle',hint:'Toggle only the approved bonus items — match HR guidelines.',ask:"Bonus eligibility flags need to match the policy doc — toggle them correctly.",reward:'"...matches policy. Precisely."'},
   {type:'voicemail',pool:['invoice','payment','transfer','balance','receipt'],ask:"Accounting voicemail had five terms — type back the last one you heard.",reward:'"...correct. Every word matters."'},
   {type:'frequency',target:97,hint:'Tune to 97 FM for the payroll compliance broadcast.',ask:"Tune the office radio to 97.0 — compliance update is broadcasting now.",reward:'"...97.0. On time. Always."'},
   {type:'conveyor',target:'📄',fakes:['📧','📁','📊'],ask:"Payslips coming off the printer belt — catch only the payslips, nothing else.",reward:'"...all payslips caught. Not one misfiled."'},
   {type:'gauge',ask:"Tax calculation is running — watch the progress gauge and stop it exactly at 100%. Not 99. Not 101.",reward:'"...100.0. Precisely. Of course."'},
   {type:'patchline',pairs:[['Sonja','Payroll extension'],['Nino','Director line'],['HR','Compliance desk']],hint:'Drag a line from each person to their extension.',ask:"Phone routing got reset again. Patch each person back to their correct line.",reward:'"...patched. Quietly efficient."'},
   {type:'circuit',ask:"Accounting software threw a fault — trace the circuit to find the broken connection.",reward:'"...found it. Third node. Fixed."'},
   {type:'cableroute',ask:"Server room cables got shuffled during the audit — route the payroll server back to the right port.",reward:'"...correct port. Payroll system online."'},
   {type:'wordle',word:'GROSS',ask:"Payroll term. Five letters. You should know this one.",reward:'"...GROSS. Yes. Before deductions."'},
   {type:'minesweeper',size:4,mines:2,ask:"Budget grid — identify the safe spending areas without triggering an overage.",reward:'"...all clear. Budget intact."'},
   {type:'hidden',items:[{label:'Payslip',emoji:'📄',x:70,y:80},{label:'Stamp',emoji:'🔏',x:200,y:50},{label:'Calc',emoji:'🖩',x:150,y:140}],ask:"The payslip, the approval stamp, and the calculator — somewhere on this desk.",reward:'"...found. Quietly efficient."'},
   {type:'flowfree',size:4,pairs:[{color:'#e03030',from:[0,0],to:[3,2]},{color:'#2e7d46',from:[0,3],to:[3,0]},{color:'#1565c0',from:[1,1],to:[3,3]}],ask:"Route the salary transfers through the correct bank channels — no crossings.",reward:'"...all routed. Transfers processing."'},
   {type:'typingtest',passage:'Salary transfer confirmed. Net amount: EUR 2,850.00. Reference: PAY-2024-047.',ask:"Type the salary confirmation exactly before the banking window closes.",reward:'"...sent. To the cent. As always."'},
   {type:'expenses',threshold:100,items:[{name:'Printer ink',amount:45},{name:'Team lunch',amount:85},{name:'Standing desk',amount:420},{name:'Sticky notes',amount:8},{name:'Chair upgrade',amount:290}],ask:"...review these. Approve ≤$100.",reward:'"...processed. Budget balanced."'},
   {type:'filing',files:[{name:'January payslip',cab:'Q1'},{name:'March tax',cab:'Q1'},{name:'July bonus',cab:'Q3'},{name:'October invoice',cab:'Q4'}],ask:"...file these by quarter. Quietly.",reward:'"...filed. Every quarter accounted for."'},
   {type:'elevator',floor:3,ask:"...payroll office is floor 3. Don't miss it.",reward:'"...arrived. On time. As expected."'},
   {type:'waterplant',target:50,tol:8,ask:"...water the desk plant. Not too much. It's sensitive.",reward:'"...perfect. Like the spreadsheets."'},
   {type:'receipt',items:[{name:'Salary A',price:2850},{name:'Salary B',price:3100},{name:'Salary C',price:2600},{name:'Bonus',price:500}],ask:"...add up the payroll batch total.",reward:'"...9050. Correct to the cent."'},
   {type:'schedule',meetings:[{name:'Payroll Run',slot:'9:00'},{name:'Tax Filing',slot:'11:00'},{name:'Audit Prep',slot:'14:00'},{name:'Bank Transfer',slot:'16:00'}],ask:"...schedule the finance day. No overlaps.",reward:'"...all scheduled. Quietly."'},
   {type:'namecard',names:['Accounting','Finance','HR','Legal','Payroll'],ask:"...sort the department folders alphabetically.",reward:'"...sorted. As always."'},
   {type:'rubberband',target:45,tol:8,ask:"...budget tolerance band. Stretch to 45%. Carefully.",reward:'"...within tolerance. Budget holds."'},
   {type:'coffeeorder',count:3,ask:"...three payroll clerks need coffee before the run. Remember the orders.",reward:'"...delivered. They can focus now."'},
   {type:'pingpong',rallies:4,ask:"...break room. Quick rally. Quietly.",reward:'"...four rallies. Back to payroll."'},
   {type:'firewall',rounds:5,ask:"...payroll server ports. Allow the safe ones.",reward:'"...secured. Salaries are safe."'},
   {type:'password',pw:'AUDIT',ask:"...audit system locked. Unscramble the password.",reward:'"...back in. Quietly."'}
 ]},
 pedja:{desc:'Ex-waiter, 2m tall, rookie',home:{x:4,y:3},pool:[
   {type:'timing',ask:"Holding a glass on the top shelf — say NOW at the right moment.",reward:'*hops down* "No tip, but we are good."'},
   {type:'mash',ask:"Huge lunch order — mash SPACE to carry all the trays!",reward:'"Ten plates, one hand. Waiter life."'},
   {type:'choose',q:'What does a real waiter never forget?',opts:[{t:'Who ordered what',ok:true},{t:'The wifi pass',ok:false},{t:'His own name',ok:false}],ask:"Quiz me, what does a pro never mess up?",reward:'"Exactly. Old habits."'},
   {type:'catch',ask:"Trays are falling off the counter — catch them!",reward:'"Not a single one dropped. Reflexes!"'},
   {type:'reflex',ask:"Order is up at the pass — grab it the second the bell rings.",reward:'"Fastest hands in the building."'},
   {type:'balance',ask:"Balance the tray of coffees across the room. Steady, tall guy.",reward:'"Not a drop spilled. Waiter mode."'},
   {type:'stack',ask:"Stack the clean plates without toppling them.",reward:'"Neat tower. Just like the old job."'},
   {type:'whack',ask:"Buzzers going off at every table — tap them fast!",reward:'"Served all six. Big tip energy."'},
   {type:'qte',ask:"Rush hour combo — fire off the orders in sequence!",reward:'"Flawless service. Chef kiss."'},
   {type:'moving',ask:"The lunch delivery guy keeps wandering — catch him, three taps!",reward:'"Got him. Food is safe."'},
   {type:'stopwatch',ask:"Espresso needs exactly 3 seconds. Stop the clock dead on.",reward:'"Perfect shot. Barista blood."'},
   {type:'jenga',ask:"Clear the stacked chairs without toppling the whole pile.",reward:'"Not one chair fell. Two meters of pure control."'},
   {type:'maze',ask:"Weave the food cart through the packed lunch crowd.",reward:'"Delivered hot. Never spilled a drop."'},
   {type:'signal',ask:"The kitchen bell rings on a rhythm — catch it at the peak.",reward:'"Order is up, right on the beat."'},
   {type:'pairs',ask:"Match each table number to its order ticket.",reward:'"All matched. Old habits really do stick."'},
   {type:'overload',ask:"Two tables calling at once — keep them both happy.",reward:'"Both served. Waiter reflexes never left."'},
   {type:'priority',cards:[{l:'Food is getting cold',p:1},{l:'Refill drinks',p:2},{l:'Wipe table 4',p:3},{l:'Chat with regulars',p:4}],hint:'Waiter instincts: what first?',ask:"Rush hour test: what does a waiter do first?",reward:'"Cold food is a crime. You get it."'},
   {type:'recipe',ask:"Old waiter skills — make the boss's coffee to the exact recipe.",reward:'"Nailed the measures. Some things you don\'t forget."'},
   {type:'park',ask:"New guy job: park the client's car in the bay. No scratches, please.",reward:'"Parked clean. Rookie\'s earning his keep."'},
   {type:'scrub',ask:"Give the showroom car a wash — scrub every dirty patch.",reward:'"Spotless. I miss bussing tables less now."'},
   {type:'checklist',items:['Tires','Fuel','Lights','Mirrors','Paperwork'],ask:"Delivery vehicle needs the full check before it leaves. Every item, fast.",reward:'"All checked. Ready to roll."'},
   {type:'gauge',ask:"Fill the tank for delivery — don't overshoot, don't undershoot.",reward:'"Tank\'s full. Didn\'t spill a drop, this time."'},
   {type:'count',ask:"Count what's missing from the supply shelf and restock exactly that much.",reward:'"Shelf\'s full again. Rookie delivers."'},
   {type:'flowchart',tree:{q:'Table needs attention?',yes:{q:'Food or service issue?',yes:{end:true,win:true},no:{end:true,win:false}},no:{q:'Pre-clean next table?',yes:{end:true,win:true},no:{end:true,win:false}}},hint:'Follow the waiter decision tree.',ask:"Walk me through the waiter decision tree — test your instincts.",reward:'"Right call. Old habits."'},
   {type:'hotkey',items:[{k:'T',l:'Tables'},{k:'K',l:'Kitchen'},{k:'M',l:'Manager'},{k:'B',l:'Bar'}],target:'K',ask:"Rush hour call — keyboard only. Where do I route this order?",reward:'"Kitchen gets it. No fumbling."'},
   {type:'heatmap',zones:['Burger station','Drinks bar','Dessert shelf','Register'],hotIdx:0,hint:'Which station gets the most customer attention during lunch?',ask:"Check the lunch rush heatmap — which station has the most traffic right now?",reward:'"Burger station always. Never changes."'},
   {type:'conveyor',target:'\uD83C\uDF7D',fakes:['\uD83E\uDDD2','\uD83E\uDDE2','\uD83D\uDCF1'],ask:"Plates coming off the kitchen belt fast — grab only the food plates, not the junk.",reward:'"Five plates, zero drops. Beautiful."'},
   {type:'slot',target:[0,0,0],hint:'Stop all three reels on the money sign.',ask:"Triple tips day! Stop the reels on the jackpot — all three match.",reward:'"Jackpot shift. Best day ever."'},
   {type:'pricetag',items:[{name:'House special',price:'€14'},{name:'Side salad',price:'€5'},{name:'Espresso',price:'€2'}],hint:'Drag each price to the right menu item.',ask:"New menu, new prices — drag each price tag to the right dish before service starts.",reward:'"Correct prices. Service ready."'},
   {type:'whiteboard',pts:[[20,80],[80,30],[160,50],[220,110],[160,150]],ask:"Draw the delivery route on the whiteboard map — hit every stop in order.",reward:'"Route mapped. Efficient. Rookie instincts."'},
   {type:'rhythm',ask:"Kitchen prep has a rhythm — tap along to keep pace with the orders. Old habit.",reward:'"In the groove. Chef would be proud."'},
   {type:'slider',ask:"Find the sweet spot on the sauce recipe — not too much, not too little. Feel it out.",reward:'"Perfect balance. Two years of that trains the hand."'},
   {type:'higherlower',ask:"Guess the table number the big order went to. I\'ll say warmer or colder.",reward:'"Table 12. Waiter memory never fades."'},
   {type:'voltage',ask:"Kitchen equipment on three circuits — keep them all green during the dinner rush.",reward:'"All green. Didn\'t blow a single breaker."'},
   {type:'oddeven',ask:"Odd tables get the fixed menu, even tables get à la carte. Sort them fast.",reward:'"Split perfectly. Old instincts, new job."'},
   {type:'wordle',word:'TABLE',ask:"Five letters. Where I spent five years of my life. Guess it.",reward:'"TABLE. Yeah. Good times, low pay."'},
   {type:'minesweeper',size:5,mines:4,ask:"Kitchen floor has wet spots — map the safe path to the service station without slipping.",reward:'"Safe route found. No incidents. Waiter instincts."'},
   {type:'hidden',items:[{label:'Tray',emoji:'🍽️',x:90,y:60},{label:'Timer',emoji:'⏱️',x:220,y:130},{label:'Ticket',emoji:'🎫',x:140,y:160}],ask:"Lost the service tray, the kitchen timer, and a table ticket. Classic Pedja.",reward:'"All found. Service resumes."'},
   {type:'merge2048',target:64,ask:"Table numbers are getting doubled up — merge them before service starts.",reward:'"Sorted. Clean floor plan. Ready to serve."'},
   {type:'flowfree',size:4,pairs:[{color:'#e03030',from:[0,0],to:[3,1]},{color:'#2e7d46',from:[0,3],to:[2,0]},{color:'#b07d18',from:[1,2],to:[3,3]}],ask:"Route the food orders from kitchen to tables without blocking the aisle.",reward:'"Every table served. Zero collisions. Waiter brain."'},
   {type:'tetris',lines:4,ask:"Stockroom delivery just came in — stack the boxes to clear space. Four rows at least.",reward:'"Four rows cleared. I have a gift for this apparently."'},
   {type:'typingtest',passage:'Table 4 ordered two specials, one soup, and three espressos.',ask:"Read back the order ticket to the kitchen — type it exactly before they start the wrong dish.",reward:'"Perfect read-back. Chef didn\'t even glare."'},
   {type:'stapler',beats:4,bpm:100,ask:"Staple these menus to the beat. Four staples, steady rhythm.",reward:'"Clean staples. The menus look professional."'},
   {type:'stamp',docs:['Health cert','Fire safety','Liquor license','Food handling'],ask:"Restaurant inspection — stamp these compliance docs in order.",reward:'"All stamped. Inspector leaves happy."'},
   {type:'shredder',docs:['Old menu','Broken receipt','Customer complaint','Health code cert','Napkin doodle'],keep:'Health code cert',ask:"Shred the old restaurant stuff. Keep the health code!",reward:'"Good. That cert is our lifeline."'},
   {type:'phonetree',target:'International',ask:"Calling the supplier — navigate the phone menu to International orders.",reward:'"Connected. Ordering those special plates from Italy."'},
   {type:'coffeeorder',count:4,ask:"Table of four just ordered drinks. Remember every single one.",reward:'"Four drinks, perfect recall. Old muscle memory."'},
   {type:'receipt',items:[{name:'Appetizer',price:8},{name:'Main x2',price:24},{name:'Dessert',price:7},{name:'Coffee x3',price:9},{name:'Wine',price:15}],ask:"Table's bill — add it up before they get impatient.",reward:'"63 total. Tip not included. Waiter math never dies."'},
   {type:'pingpong',rallies:6,ask:"Break room ping pong — keep the rally alive. 2m reach is an advantage.",reward:'"Six rallies. Nobody can reach my serves."'},
   {type:'schedule',meetings:[{name:'Morning Prep',slot:'9:00'},{name:'Service Training',slot:'11:00'},{name:'Lunch Rush',slot:'13:00'},{name:'Cleanup',slot:'16:00'}],ask:"Schedule the restaurant day. Old habits — everything on time.",reward:'"Shift schedule locked. Service runs smooth."'},
   {type:'rubberband',target:70,tol:10,ask:"Stretch the tablecloth tight — 70% tension. Don't rip it.",reward:'"Perfect tension. The table looks immaculate."'}
 ]},
 nina:{desc:"Boss's daughter, control freak",home:{x:13,y:9},pool:[
   {type:'simon',ask:"Do EXACTLY as I say, in order. Because I am always right. Repeat.",reward:'"See? Works when you listen to ME."'},
   {type:'type',word:'YES NINA',ask:"Type it. You know the magic words.",reward:'*smiles* "Good. Was not hard, was it."'},
   {type:'choose',q:'Nina says the sky is green. You say:',opts:[{t:'"You are right, Nina."',ok:true},{t:'"It is blue."',ok:false},{t:'Say nothing',ok:false}],ask:"The sky is green today. RIGHT?",reward:'"Obviously. I am always right."'},
   {type:'sequence',ask:"Repeat my priority list. In MY order. Exactly.",reward:'"Finally, someone competent."'},
   {type:'avoid',ask:"Approve MY ideas, reject everyone else's.",reward:'"Correct. My ideas are the best ideas."'},
   {type:'colormatch',ask:"Match the brand color I picked. It is the only right one.",reward:'"Obviously. My taste is flawless."'},
   {type:'trace',ask:"Follow my org chart, top to bottom. Me near the top.",reward:'"Good. Now you know the hierarchy."'},
   {type:'lockpick',ask:"Get into Dad's office. I am allowed. I said so.",reward:'"See? Rules do not apply to me."'},
   {type:'impostor',word:'YES NINA',odd:'actually, no',hint:'Four agree with her. Find the traitor.',ask:"Someone disagreed with me. Find the traitor.",reward:'"Knew it. Nobody disagrees with me."'},
   {type:'reverse',ask:"Now do my instructions BACKWARDS. Keep up. I invented this.",reward:'"Acceptable. I made you better today."'},
   {type:'gridmem',ask:"Memorize MY new seating chart. There will be a test. This is it.",reward:'"Correct. I assign, you remember."'},
   {type:'rank',items:["Nina's idea","Dad's idea","Client's request",'YOUR idea'],hint:'Drag to reorder. Hers goes first. Obviously.',ask:"Sort these by importance — mine first, obviously.",reward:'"Correct order. Mine is always first."'},
   {type:'echo',ask:"Repeat my growing list of demands. Don't fall behind.",reward:'"Good. You kept up with all of them."'},
   {type:'crack',ask:"Guess what I'm REALLY thinking. Hint: I'm always right.",reward:'"You got it eventually. Slow, but fine."'},
   {type:'forge',recipe:["NINA'S VISION",'EXECUTION','CREDIT TO NINA'],extra:['TEAM CREDIT','HUMILITY'],ask:"Combine everyone's ideas so mine comes out on top.",reward:'"See? Mine wins every time. As it should."'},
   {type:'overload',ask:"I need two things done AT ONCE. Both are urgent. Obviously.",reward:'"Finally, someone who can multitask like me."'},
   {type:'noise',real:'Nina approved this',fakes:['Team approved this','Nino approved this','Client approved this','HR approved this'],hint:'Find the only approval that counts.',ask:"Find the ONLY approval that matters in this pile.",reward:'"Correct. Mine. The rest are suggestions."'},
   {type:'dragfile',ask:"These files are in the WRONG folders. Fix it. Properly. My way.",reward:'"Finally organized. Was that so hard?"'},
   {type:'inspect',ask:"Inspect the returned vehicle — find every scratch. Miss nothing.",reward:'"Three flaws. I\'d have found a fourth. Good enough."'},
   {type:'arrange',items:[['🪑','chair'],['📽️','proj'],['💻','laptop']],hint:'Drag each item onto its marked spot. My way, exactly.',ask:"Set up the meeting room. Chair, projector, laptop — precisely where I want them.",reward:'"Perfect. Finally, someone who listens."'},
   {type:'pincode',ask:"Memorize the conference dial-in code. I will not repeat it. I already didn't.",reward:'"Correct. Obviously. I chose that code."'},
   {type:'crossword',clues:[{hint:'Top of the org chart (name)',ans:'NINA'},{hint:'Runs payroll (name)',ans:'SONJA'},{hint:'Always out of office (name)',ans:'TEONEM'}],ask:"Fill in my org chart crossword. My way. Correctly.",reward:'"Correct. Obviously."'},
   {type:'budgetslider',targets:[60,25,15],labels:['My projects','Team','Misc'],ask:"Set the project budget allocation. My priorities first. Obviously.",reward:'"Perfect percentages. Finally."'},
   {type:'voltage',ask:"Running three approval processes simultaneously — keep all systems green until they finish.",reward:'"All approved. Simultaneously. Flawlessly."'},
   {type:'heatmap',zones:['My desk','Meeting room','Coffee corner','Entrance'],hotIdx:0,hint:'Where is the most important activity in this office happening?',ask:"Office heatmap — identify where the most critical work happens. Obviously.",reward:'"My desk. Obviously. Good."'},
   {type:'anagram',word:'REVIEW',ask:"Unscramble what I demand from everyone before anything ships.",reward:'"REVIEW. Yes. Obviously. Always."'},
   {type:'mirror',word:'APPROVE',ask:"My screen flipped again. Type APPROVE normally — display is mirrored.",reward:'"Approved. Even in mirror mode I am in control."'},
   {type:'pricetag',items:[{name:'Premium seat',price:'€200'},{name:'Standard seat',price:'€80'},{name:'Basic seat',price:'€40'}],hint:'Drag the price tags to the conference seats.',ask:"Conference room seating — drag the right price tag to each tier before clients arrive.",reward:'"Correct pricing. Premium goes to me, obviously."'},
   {type:'rolodex',cards:['Nino — Director','Sonja — Payroll','Daniel — Design','Me — Basically everything'],correctIdx:3,ask:"Who actually runs this company? Scroll to the right card. Obviously.",reward:'"Me. Obviously. I\'m glad we agree."'},
   {type:'voicemail',pool:['approved','rejected','pending','revised','escalated'],ask:"Five status updates on my voicemail — type back the last one. I delete as I go.",reward:'"Correct. Escalated. As it should be."'},
   {type:'wire',pairs:[['Nina','Final approval'],['Nino','Budget sign-off'],['Sonja','Payroll processing']],hint:'Connect each person to their actual responsibility.',ask:"New org chart — wire each person to their real role. My role is obvious.",reward:'"Wired correctly. Finally, clarity."'},
   {type:'cableroute',ask:"Conference room AV got scrambled before my presentation — route the signal back to the main screen.",reward:'"Connected. Presentation will be flawless. Obviously."'},
   {type:'approvalchain',chain:['Employee','Manager','Nina','Nino'],hint:'Every request goes through Nina before Nino. Obviously.',ask:"Someone submitted a request skipping me. Show them the correct approval chain.",reward:'"Through ME first. Always. Obviously."'},
   {type:'wordle',word:'RIGHT',ask:"Five letters. What I always am. You should get this immediately.",reward:'"RIGHT. Obviously. First try? Acceptable."'},
   {type:'minesweeper',size:4,mines:2,ask:"Meeting room booking grid — clear the available slots without double-booking my time.",reward:'"My time protected. Obviously."'},
   {type:'hidden',items:[{label:'Stamp',emoji:'✅',x:60,y:50},{label:'Remote',emoji:'📡',x:210,y:120},{label:'Marker',emoji:'🖍️',x:160,y:80}],ask:"My approval stamp, presentation remote, and marker are missing. Obviously someone moved them.",reward:'"Found. I\'ll be putting these in a locked drawer now."'},
   {type:'merge2048',target:128,ask:"Combine the project scores until they reach my minimum acceptable threshold.",reward:'"128. My minimum. Obviously achieved."'},
   {type:'flowfree',size:4,pairs:[{color:'#e03030',from:[0,0],to:[3,3]},{color:'#2e7d46',from:[0,2],to:[3,0]},{color:'#b07d18',from:[1,3],to:[3,1]}],ask:"Route the approval flows — every request must pass through the right chain. No shortcuts.",reward:'"All approved via the correct chain. Obviously."'},
   {type:'typingtest',passage:'This proposal is rejected. Please revise and resubmit by Friday.',ask:"Type my feedback email word for word. My rejection letters must be pristine.",reward:'"Sent. Devastating, yet professional. Obviously."'},
   {type:'pipe',size:4,ask:"Conference room AV routing is wrong again — rotate the signal pipes to connect source to screen. Obviously.",reward:'"Signal connected. Presentation will be flawless. Obviously."'},
   {type:'copier',rounds:5,ask:"Five copies of MY report. Green means go. Obviously.",reward:'"Five perfect copies. As expected."'},
   {type:'filing',files:[{name:'Meeting notes',cab:'Management'},{name:'Koda vet bill',cab:'Personal'},{name:'Budget proposal',cab:'Finance'},{name:'Team review',cab:'Management'}],ask:"File these. Get one wrong and I tell my father. Obviously.",reward:'"All correct. I trained you well. Obviously."'},
   {type:'expenses',threshold:300,items:[{name:'Designer bag',amount:1200},{name:'Team workshop',amount:280},{name:'Koda grooming',amount:95},{name:'Office art',amount:450},{name:'Stationery',amount:30}],ask:"Approve expenses under $300. I decide what's reasonable. Obviously.",reward:'"Budget approved. My standards are impeccable."'},
   {type:'stapler',beats:5,bpm:140,ask:"Staple my reports to MY rhythm. Five staples, fast and precise. Obviously.",reward:'"Perfectly stapled. You may go."'},
   {type:'schedule',meetings:[{name:'Morning Briefing',slot:'9:00'},{name:'Performance Review',slot:'11:00'},{name:'Lunch with Father',slot:'13:00'},{name:'Team Critique',slot:'15:00'}],ask:"My schedule. Place everything correctly. I don't repeat myself. Obviously.",reward:'"Perfect schedule. You\'re learning. Obviously."'},
   {type:'coffeeorder',count:3,ask:"Three drinks for my meeting. Memorize them. Get one wrong and it's over. Obviously.",reward:'"All correct. You may fetch them now."'},
   {type:'namecard',names:['Board Member','CEO','CFO','COO','CTO'],ask:"Sort my executive contacts. Alphabetical. Obviously.",reward:'"Sorted. These are the only people that matter."'},
   {type:'receipt',items:[{name:'Koda treats',price:22},{name:'Designer pen',price:45},{name:'Planner',price:18},{name:'Scarf',price:85}],ask:"My personal expense receipt. Add it up. Don't question the items. Obviously.",reward:'"170. Father will reimburse. Obviously."'},
   {type:'pingpong',rallies:4,ask:"Ping pong in the break room. Don't let me lose. Obviously.",reward:'"I won. As expected. Obviously."'}
 ]},
 daniel:{desc:'Designer, chill, big vibes',home:{x:4,y:5},pool:[
   {type:'choose',q:'Which design has the best vibe?',opts:[{t:'Clean & minimal',ok:true},{t:'5 fonts, 3 gradients',ok:false},{t:'Default bootstrap',ok:false}],ask:"Yo, which design has the best vibe? Just feel it. *smoke*",reward:'*thumbs up through haze* "Flawless vibe, respect."'},
   {type:'timing',ask:"Exporting the artboard — catch the perfect frame, man.",reward:'"Buttery. Respect."'},
   {type:'memory',ask:"Remember my palette order? Play it back, keep the vibe.",reward:'"Palette locked. Immaculate."'},
   {type:'scramble',word:'PIXELS',ask:"Unscramble what I obsess over.",reward:'*slow nod* "Yeah man. Every one of them."'},
   {type:'catch',ask:"Loose layers floating off the canvas — catch them, gently.",reward:'"Caught the vibe AND the layers. Respect."'},
   {type:'colormatch',ask:"Yo, match this hex to the vibe swatch, man.",reward:'"That is the one. Pure harmony."'},
   {type:'wire',pairs:[['--bg-primary','Canvas layer'],['--accent','CTA button'],['--muted','Placeholder text']],hint:'Connect each token to its layer.',ask:"Connect the color tokens to their layers. Keep it flowing.",reward:'"All wired up. The system breathes now."'},
   {type:'rhythm',ask:"Design has a rhythm too. Tap the grid beat.",reward:'"Yeah man. You feel the flow."'},
   {type:'spotdiff',ask:"One pixel is off in this row. Find it, it is killing me.",reward:'"THERE. Thank you. I can sleep now."'},
   {type:'reverse',ask:"Play my palette back... in reverse. Trust the process.",reward:'"Backwards AND beautiful. Deep."'},
   {type:'pairs',ask:"Match the color pairs, man. They belong together.",reward:'"Reunited. The canvas is at peace."'},
   {type:'stopwatch',ask:"Stop the render at exactly 3 seconds. The perfect frame lives there.",reward:'"Frame-perfect. That is art."'},
   {type:'forge',recipe:['BASE NAVY','WARM ACCENT','SOFT GLOW'],extra:['NEON GREEN','COMIC SANS'],ask:"Mix the brand palette in the right order — this matters, man.",reward:'"That gradient is *chef kiss*. Pure alchemy."'},
   {type:'noise',ask:"One layer is aligned right, the rest are off-grid. Find it.",reward:'"There. My eye was twitching. Fixed."'},
   {type:'maze',ask:"Route this shape through the canvas without clipping anything.",reward:'"Smooth path. No clipping. Respect."'},
   {type:'colormatch',ask:"Match each element to its drop-shadow style.",reward:'"Every shape found its shadow. Beautiful."'},
   {type:'signal',ask:"Catch the animation at its peak frame — that's the money shot.",reward:'"That is THE frame. Ship it."'},
   {type:'impostor',word:'#2E4A72',odd:'#2E4B72',hint:'Four identical hex codes. One is off by a digit.',ask:"One hex code is off by ONE digit and it is ruining my life. Find it.",reward:'"THERE. One digit. Chaos averted. Respect."'},
   {type:'proofread',ask:"Client ad has a typo somewhere, man. Find it before it ships.",reward:'"Caught it. Crisis averted. Respect."'},
   {type:'stack',ask:"Pack these prints into the shipping box, man — stack it steady, don't crush the corners.",reward:'"Boxed clean. Art survives shipping."'},
   {type:'splice',pairs:[['Poster set A','Box 1'],['Poster set B','Box 2'],['Poster set C','Box 3']],hint:'Match each label to the right box.',ask:"Label these boxes right, man, or the wrong client gets the wrong art.",reward:'"All matched. Aesthetic AND logistics. Respect."'},
   {type:'proofread',ask:"One more typo hunt — the slide deck footer this time, man. Find it.",reward:'"Clean. Ship it before anyone notices there was one."'},
   {type:'cableroute',ask:"Route the USB from my laptop to the projector — no crossing walls, man.",reward:'"Powered up. Design can begin."'},
   {type:'typewriter',word:'VIBES',ask:"Type the most important concept in design — letter by letter, man.",reward:'"VIBES confirmed. You understand."'},
   {type:'cipher',shift:2,raw:'DESIGN',ask:"Client encoded their brief. Shift 2 letters — which shift value cracks it?",reward:'"Decoded. Now I can feel the brief, man."'},
   {type:'wordsearch',words:['HUE','VIBE','FONT'],ask:"Find the three design fundamentals in this letter grid, man.",reward:'"All found. Typography is everywhere if you look."'},
   {type:'anagram',word:'CLIENT',ask:"Unscramble the most important word in my vocabulary, man.",reward:'"CLIENT. The whole reason we exist."'},
   {type:'toggle',hint:'Toggle the right export switches — only PNG and SVG on.',ask:"Export settings got reset — toggle back to PNG and SVG only. Nothing else.",reward:'"Export clean. File system thanks you."'},
   {type:'whiteboard',pts:[[30,40],[120,20],[200,80],[160,140],[80,130]],ask:"Sketch the design flow on the whiteboard — connect the dots in order.",reward:'"Flow is mapped. Beautiful process."'},
   {type:'anagram',word:'CANVAS',ask:"Unscramble the word for my workspace. It\'s also an app I built.",reward:'"CANVAS. Obviously. Named it myself."'},
   {type:'whiteboard',pts:[[30,30],[130,20],[220,70],[200,140],[100,150]],ask:"Storyboard the client presentation — connect the slides on the whiteboard in order.",reward:'"Flow is perfect. Client won\'t know what hit them."'},
   {type:'binary',val:10,ask:"The client\'s revision count is 10 — flip the binary light panel to match.",reward:'"Ten revisions in binary. The client\'s lucky I\'m patient."'},
   {type:'park',ask:"Design expo parking — squeeze the van (with all the equipment) into the last spot. Don\'t scratch the vibe.",reward:'"Parallel parked. The equipment is safe. The vibe is intact."'},
   {type:'cash',ask:"Client paid the invoice in cash — count it out and confirm before I issue the receipt.",reward:'"Counted. Exact. Even the design industry runs on money, man."'},
   {type:'moving',ask:"New office layout — catch the furniture pieces as they move into the right spots.",reward:'"Every piece landed right. Space has intention now."'},
   {type:'qte',ask:"Client presentation combo — advance slides, dim lights, click demo, all in sequence. Go.",reward:'"Flawless execution. The room was speechless."'},
   {type:'redact',sentences:['Client budget: €45,000 for full rebrand','Contact: Ana Kovač, CEO +385 99 111 2233','Deadline: confidential — before competitor launch'],sensitive:['€45,000','Ana Kovač, CEO +385 99 111 2233','confidential'],ask:"Agency brief before sending to the printer — redact the sensitive bits.",reward:'"Redacted. Brief is clean. Printer gets the safe version."'},
   {type:'wordle',word:'PIXEL',ask:"Five letters. The smallest unit of my universe. You know this one.",reward:'"PIXEL. Obviously. I think in them."'},
   {type:'minesweeper',size:5,mines:3,ask:"Design grid with broken nodes — find the safe layout zones without triggering a client complaint.",reward:'"Clean grid. Zero broken layouts. Designer magic."'},
   {type:'hidden',items:[{label:'Stylus',emoji:'✏️',x:80,y:60},{label:'Tablet',emoji:'📱',x:220,y:100},{label:'Swatch',emoji:'🎨',x:130,y:160}],ask:"Lost my stylus, drawing tablet, and color swatch before the client meeting. Very chill about it.",reward:'"Found everything. Vibes restored. Let\'s create."'},
   {type:'merge2048',target:256,ask:"Layer complexity — merge the design iterations until the concept reaches full resolution.",reward:'"256. Full resolution. The client will love it."'},
   {type:'flowfree',size:5,pairs:[{color:'#e03030',from:[0,0],to:[4,4]},{color:'#2e7d46',from:[0,4],to:[4,0]},{color:'#1565c0',from:[2,0],to:[2,4]},{color:'#b07d18',from:[0,2],to:[4,2]}],ask:"Connect the design system tokens to their components — every cell must flow.",reward:'"Fully connected system. Every token placed. Beautiful."'},
   {type:'tetris',lines:3,ask:"Artboard layers are piling up in the wrong order — stack them clean. Three layers cleared.",reward:'"Layer stack is immaculate. The file is breathable now."'},
   {type:'typingtest',passage:'Final designs attached. Please review by EOD and confirm approval.',ask:"Type the handoff email to the client. Clean copy, no typos — this is the final impression.",reward:'"Sent. Professional. The client will feel the care."'},
   {type:'pipe',size:4,ask:"Design file export pipeline broke — rotate the nodes to reconnect the output stream.",reward:'"Export flowing. Files delivered. Smooth."'},
   {type:'waterplant',target:60,tol:10,ask:"Water the studio succulent. Too much = dead vibes.",reward:'"Perfect hydration. The succulent thrives."'},
   {type:'password',pw:'FIGMA',ask:"Design tool locked. Unscramble the password, dude.",reward:'"Back in. The artboard awaits."'},
   {type:'stamp',docs:['Concept Art','Wireframe','Mockup','Final Export'],ask:"Stamp the design deliverables in the right order.",reward:'"Stamped in order. The process is beautiful."'},
   {type:'shredder',docs:['Old mockup','Draft logo','Brand guidelines','Sketch v1','Napkin idea'],keep:'Brand guidelines',ask:"Shred the old iterations. Keep the brand guidelines though.",reward:'"Clean desk. Brand intact. Vibes immaculate."'},
   {type:'coffeeorder',count:3,ask:"Three designers need their morning fuel. Remember the vibes... I mean the orders.",reward:'"All correct. Caffeinated creativity incoming."'},
   {type:'schedule',meetings:[{name:'Moodboard',slot:'9:00'},{name:'Client Pres',slot:'11:00'},{name:'Design Crit',slot:'14:00'},{name:'Wrap-up',slot:'16:00'}],ask:"Schedule the design day. Don't stack critiques — we need breathing room.",reward:'"Clean calendar. Space for inspiration."'},
   {type:'receipt',items:[{name:'Pen set',price:28},{name:'Sketchbook',price:15},{name:'Markers',price:32},{name:'Color swatches',price:12}],ask:"Art supply receipt. Add it up for the reimbursement.",reward:'"87. Worth every cent for the craft."'},
   {type:'pingpong',rallies:5,ask:"Creative break — ping pong clears the mind. Keep the rally, dude.",reward:'"Five rallies. Brain reset. Ready to design."'},
   {type:'rubberband',target:50,tol:12,ask:"Stretch the canvas frame tension to 50%. Snap it and the canvas is ruined.",reward:'"Perfect tension. Canvas is gallery-ready."'}
 ]},
};

// Ambient "thought bubble" lines — fire randomly while an NPC is just standing/wandering,
// no interaction needed. Pure flavor, matches each character's `desc` trait.
const IDLE_LINES={
  dejan:["Need a smoke in 5.","Gromix compiles... probably.","One more coffee.","Where's my lighter...","Terrace. Now."],
  teonem:["Client's calling again.","'Out in town', as always.","Big deal closing, trust me.","Gotta run — meeting.","Sales never sleeps."],
  steve:["*vape cloud*","Zagreb client's happy.","Beard's getting long.","Croatia's booming, boss.","One more puff."],
  brana:["...I see everything.","Noted. *writes it down*","Watching. Always watching.","Interesting... very interesting.","Nothing gets past me."],
  sonja:["Payroll doesn't run itself.","Numbers check out.","Quiet day, good day.","Don't ask me twice.","Almost done reconciling."],
  pedja:["Two meters of nerves.","Still learning the ropes.","Was easier waiting tables.","Hope I don't mess this up.","Getting the hang of it!"],
  nina:["This desk needs realigning.","Everything has its place.","Dad's watching, be sharp.","Control the chaos.","Not good enough. Again."],
  daniel:["*adjusts palette* ...nice.","Big vibes today, man.","This gradient though.","Design's basically therapy.","Feeling the flow."],
};
function randIdleLine(id){const arr=IDLE_LINES[id];return arr?arr[Math.floor(Math.random()*arr.length)]:'';}

